services:
  location-simulator:
    build: .
    container_name: multi-platform-location-simulator
    ports:
      - "8080:5000"
    volumes:
      # Mount current directory for development (optional)
      - .:/app
      # Mount usbmux socket for iOS device communication (macOS path)
      - /private/var/run/usbmuxd:/var/run/usbmuxd
    privileged: true
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      # Connect to host ADB server for Android devices (Docker on macOS compatibility)
      - ADB_SERVER_SOCKET=tcp:host.docker.internal:5037
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
